import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import Layouts from "@/layouts/layouts";

const poppinsFonts = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppinsFonts.className} h-full antialiased bg-clear-off-white scroll-smooth`}
    >
      <body className="min-h-full flex flex-col">
        <Layouts>{children}</Layouts>
      </body>
    </html>
  );
}
